### ISSUE TITLE
Session is not initialized.

### ISSUE THREAD

**Issue by hyperitycorp-suny** [JosephNK/flutter_kakao_login#24]
가이드대로 모든 절차를 다 했는데도
logIn() 함수 호출 시  아래와 같은 에러가 발생합니다.

2020-01-14 15:07:11.964 814-938/com.hyperitycorp.app.inside E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Session is not initialized. Call KakaoSDK#init first., null)

테스트 단말은 안드로이드구요

빠진 설정이 있을까요?

**Comment by amondnet** [comment]
@hyperitycorp-suny 
설정 하신 내용이나 코드를 알려주실 수 있을까요? 해당 로그만으로는 파악이 어렵습니다.

- flutter doctor -v 실행결과: 
- simulator or real device?: 
- code or steps to reproduce ( full steps to reproduce so that we can reproduce the problem. )
- flutter run --verbose 로 실행한 log

등이 있으면 문제해결에 도움이 될거 같습니다.

**Comment by hyperitycorp-suny** [comment]
AndroidManifest.xml 설정 말고 따로 필요한 설정이 더 있나요?
Real device로 테스트 했구요
에러 풀 로그는 다음과 같습니다.
flutter doctor 결과로 특이사항은 없구요
가이드대로 빠짐없이 설정하였어요.

다만 AndroidManifest.xml에
<application
        android:name="io.flutter.app.FlutterApplication"
        android:label="blurry"
        android:icon="@mipmap/ic_launcher">
저는 위와 같은데 예제 샘플 코드 보니까 GlobalApplication으로 되어 있더라구요.

2020-01-14 15:40:35.952 2731-2731/com.hyperitycorp.app.inside E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hyperitycorp.app.inside, PID: 2731
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=53293, result=-1, data=Intent { (has extras) }} to activity {com.hyperitycorp.app.inside/com.hyperitycorp.app.inside.MainActivity}: java.lang.IllegalStateException: Session is not initialized. Call KakaoSDK#init first.
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4324)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.IllegalStateException: Session is not initialized. Call KakaoSDK#init first.
        at com.kakao.auth.Session.getCurrentSession(Session.java:109)
        at com.josephnk.flutterkakaologin.FlutterKakaoLoginPlugin.onActivityResult(FlutterKakaoLoginPlugin.java:114)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
        at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
        at android.app.Activity.dispatchActivityResult(Activity.java:7235)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4320)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367) 
        at android.app.ActivityThread.-wrap19(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by myriky** [comment]
저도 예전에 잘 사용하다가 갑자기 동일한 오류가 발생하네요
버전이슈인가 싶어서 버전도 예전버전 0.3.0 까지 내려봤지만 동일한 이슈가 발생하네요

flutter 1.12.13+hotfix.5 입니다

**Comment by myriky** [comment]
https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

1.12 버전 부터 안드로이드 플러그인 관련 메이저 업데이트가 있었네요.
```
currentActivity = registrar.activity();
```
를 통해서 현재 Activity를 가져오는 부분이 deprecated 됐다고 합니다.

**Comment by myriky** [comment]
#26 일단 급한대로 작업해서 풀리퀘 해놨습니다

**Comment by JosephNK** [comment]
@myriky 
늦었지만.... 이제서야 myriky님께서 pull requests 해주신 코드 적용하여, 0.6.0 배포 하였습니다. 
감사합니다. :)
