### ISSUE TITLE
(android)실행시 오류가 발생합니다.

### ISSUE THREAD

**Issue by realrnbboy** [JosephNK/flutter_kakao_login#36]
실행하면 아래와 같이 플러그인을 로드하지 못하는 것 처럼 보이는 오류를 내고 앱이 죽습니다.

Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'io.flutter.plugin.common.PluginRegistry$Registrar io.flutter.plugin.common.PluginRegistry$Registrar.addActivityResultListener(io.flutter.plugin.common.PluginRegistry$ActivityResultListener)' on a null object reference
        at com.josephnk.flutterkakaologin.FlutterKakaoLoginPlugin.onAttachedToActivity(FlutterKakaoLoginPlugin.java:104)
        at com.josephnk.flutterkakaologin.FlutterKakaoLoginPlugin.onAttachedToActivity(FlutterKakaoLoginPlugin.java:94)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.add(FlutterEnginePluginRegistry.java:143)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:19)
        at com.benife.amfit.MainActivity.configureFlutterEngine(MainActivity.kt:12)

flutter clean, flutter pub get, 재부팅, flutter 재설치 등 시도해 보았습니다. ㅠㅠ

도움부탁드립니다.

[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.778], locale ko-KR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

**Comment by Bobby9292** [comment]
Same here! please check this issue ! :(

**Comment by JosephNK** [comment]
@realrnbboy @Bobby9292 
Recently updated. Please check again. :)
