### ISSUE TITLE
Crash when login with release apk

### ISSUE THREAD

**Issue by nguyenxuankiet262** [JosephNK/flutter_kakao_login#44]
In debug mode, it works but when i login with release mode and it crashes. This is log:
FATAL EXCEPTION: main
    Process: com..., PID: 24644
    ClientError(reason=TokenNotFound, msg=Client-side error)
        at com.kakao.sdk.auth.k.c$a.a(Unknown Source:138)
        at com.kakao.sdk.auth.k.c$a.b(Unknown Source:5)
        at com.kakao.sdk.auth.b$d.a(Unknown Source:33)
        at n.g$b$a$a.run(Unknown Source:37)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by JosephNK** [comment]
@nguyenxuankiet262 

flutter_kakao_login: ^3.2.0

The latest Kakao SDK version (2.4.2) has been applied to the flutter_kakao_login package.
This issue should be applied to Kakao ProGuard.
The description has been updated in the README file.
Note please.
